name: .NET Core
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build code
      run: dotnet build --configuration Release --no-restore
    - name: Test code 
      run: dotnet test --no-restore --verbosity normal
    - name: Publish application
      run: dotnet publish -c Release -o myApp
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "./myApp" 
