name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
      
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.x'
    
    - name: Configure
      run: cmake -B build -G "Ninja Multi-Config"
    - name: Build
      run: cmake --build build --config Release --target package
